export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const UPDATE_ITEM_SUCCES='UPDATE_ITEM_SUCCES'


export const SET_CURRENT_USER='SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';